version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: task_app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate deploy && npm run start"

volumes:
  pgdata:
